### ISSUE TITLE
Survivor name field too short for nicknames

### ISSUE THREAD

**Issue by Sanatey** [ingoclaro/kdm-companion#25]
The text fields character limit is too short to support surnames and nicknames.
Say I have a character named "Elizabeth Boshie"
With the nickname "Wise savior of the lantern"
It's currently impossible to fit that into the name text field.

Possibly extend/remove the cap. Or add an optional field for nicknames?
Possibly an option for a nickname inside the edit panel.

**Comment by ingoclaro** [comment]
Thanks for the feedback @Sanatey, I'll check increasing the length

**Comment by ingoclaro** [comment]
fixed in 5.1.1
